### ISSUE TITLE
cannot output quasiparticle data by -sdata

### ISSUE THREAD

**Issue by zhangxiaoyu2046** [abelcarreras/DynaPhoPy#35]
Hi everyone,

I want to obtain the lifetime of each phonon mode. When I tried to obtain the quasiparticle phonon data by running: 
$ dynaphopy input_file TRAJECTORY -sdata
there was an error:

> Traceback (most recent call last):
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/bin/dynaphopy", line 376, in <module>
>     calculation.write_quasiparticles_data(with_extra=args.save_extra_properties)
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/dynaphopy/__init__.py", line 1239, in write_quasiparticles_data
>     quasiparticle_data = self.get_commensurate_points_data()
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/dynaphopy/__init__.py", line 1101, in get_commensurate_points_data
>     phonopy_dos = pho_interface.obtain_phonopy_dos(self.dynamic.structure,
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/dynaphopy/interface/phonopy_link.py", line 166, in obtain_phonopy_dos
>     phonon.run_mesh(mesh)
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/phonopy/api_phonopy.py", line 1716, in run_mesh
>     self._mesh.run()
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/phonopy/phonon/mesh.py", line 303, in run
>     self._set_phonon()
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/phonopy/phonon/mesh.py", line 437, in _set_phonon
>     dynmat = run_dynamical_matrix_solver_c(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/wa9055/miniconda3/envs/phonopy2.22/lib/python3.12/site-packages/phonopy/harmonic/dynamical_matrix.py", line 1222, in run_dynamical_matrix_solver_c
>     dynmat = np.zeros((len(qpoints), len(p2s) * 3, len(p2s) * 3), dtype=np.complex64) #dtype_complex
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> numpy.core._exceptions._ArrayMemoryError: Unable to allocate 13.8 TiB for an array with shape (8400, 15000, 15000) and data type complex64

seems that the numpy array is too large to be created? my structure has 5000 atoms,  and the velocity.lammpstrj is about 14 GB.
when I switched to a fat computation node with very large RAM, there is no output after 3 days while the process was stucked somewhere of dynaphopy code.
when I tried to test on a smaller structure with less atoms (162 atoms), there was another error:

> /var/spool/slurmd/job09243/slurm_script: line 17: 83200 Segmentation fault      dynaphopy input velocity.lammpstrj -ts 0.001 -r -5 60 -sdata

I don't know where I was wrong, could someone explain a bit about the workflow of generating the quasiparticle info? Is it necessary to perform a peak analysis by $ dynaphopy input_file TRAJECTORY -pa, before I run the -sdata command?

Many thanks!

**Comment by zhangxiaoyu2046** [comment]
Thanks for your advice, I've try the Mapping RAM memory on disk (--memmap) approach, the temporary output file can be generated but the running process still terminated, seems still an Out-Of-Memory error. 

I wonder if the shape of power spectrum must be converged before doing any subsequent calculations? In my case of a graphene supercell with lammps potential,  the size of the MD supercell need to be very large, if I want the shape of power spectrum to be very smooth, and this large supercell will cost lots of RAM and cause my OOM error. 

So my question is, if I use a smaller supercell, and the power spectrum has some spikes, is this power spectrum usable? how many inaccuracy will this cause to subsequent calculations? And what is a reasonable criterion for a "good" or "acceptable" power spectrum, like how smooth it should be? Other than changing the supercell size, is there any other factors that could influence the shape of power spectrum?

Thanks again for your help.

**Comment by abelcarreras** [comment]
In principle the size of the supercell doesn't need to be so large. As long as you can capture most of the atomic correlations it should be fine. I would say that the size of the supercell for the MD should be the same size the supercell you would use for a lattice dynamics calculation to compute the force constants. To improve the smoothness of the poser spectrum you assume  ergodicity and increase the length in time of your simulation instead than in size to get a better sampling. As you increase your sampling your spectrum will become smoother. How much? this will depend on the system. As a rule of thumb the more symmetric is the crystal the less sampling you need. You will need to check the convergence with the number of time steps for this.

**Comment by zhangxiaoyu2046** [comment]
Thank you so much, dear abelcarreras. I follow your advice and use a supercell with the same size as that in the MD force constant. 
I have some further questions, 
1) when using `dynaphopy input velocity.lammpstrj -sfc renormalized_FC` to output the renormalized force constant, is it necessary to do a power spectrum or peak analysis before? or dynaphopy will do these internally by the -sfc command?
2) about the Mapping RAM memory on disk (--memmap), when I used the command:
`dynaphopy input velocity.lammpstrj  -sfc renormalized_FC --read_from 70000  --read_to 100000 --memmap`
does it means dynaphopy only use step #70000 to #100000 for generating the renormalized force constant?
The job was crashed, leaving an intermediate file "trajectory.297330", is it due to OOM (I use 2 fat nodes with 3TB of RAM in total) or something wrong in my command? 
3) I also didn't know whether my dynaphopy is installed with mpi, since it was installed via conda. 
I assume the mpi is default for the maximum entropy method (power_spectrum_algorithm=1), which is the method I used. see https://github.com/abelcarreras/DynaPhoPy/issues/9. 
how can I check whether the dynaphopy is running with mpi? by ssh to the working nodes to monitor the job cpu usage?
Will mpi/serial cause any difference in the assignment of RAM in my fatnode? that could probably explain why my job always terminate.
Many thanks in advance. :-)
