### ISSUE TITLE
RuntimeError when trying to project power spectra on phonon mode

### ISSUE THREAD

**Issue by DjordjeDangic** [abelcarreras/DynaPhoPy#7]
Hello,

I have started recently using this code to calculate phonon properties from MD simulations. I am using LAMMPS software to perform MD simulation. I get a trajectory of atomic motion for fairly large cell (2k atoms) for 100 k timesteps with 1fs timestep. 

I calculate FORCE SETS using phonopy for 8 times smaller cell (phonopy cell is 5x5x5 and MD cell is 10x10x10). When I try calculating phonon band structure with phonopy using these force sets I get reasonably good agreement with DFT. If I try to calculate power spectra projected on phonon modes using Dynaphopy I get following error:

Traceback (most recent call last):
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/phonopy/api_phonopy.py", line 2951, in _build_primitive_cell
    self._supercell, trans_mat, self._symprec)
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/phonopy/structure/cells.py", line 49, in get_primitive
    return Primitive(supercell, primitive_frame, symprec=symprec)
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/phonopy/structure/cells.py", line 356, in __init__
    self._primitive_cell(supercell)
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/phonopy/structure/cells.py", line 415, in _primitive_cell
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/bin/dynaphopy", line 343, in <module>
    calculation.write_power_spectrum_phonon(args.save_phonon_mode[0])
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/dynaphopy/__init__.py", line 1030, in write_power_spectrum_phonon
    self.get_power_spectrum_phonon(),
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/dynaphopy/__init__.py", line 716, in get_power_spectrum_phonon
    (power_spectrum_functions[self.parameters.power_spectra_algorithm])[0](self.get_vq(),
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/dynaphopy/__init__.py", line 632, in get_vq
    self._vq = projection.project_onto_phonon(self.get_vc(), self.get_eigenvectors())
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/dynaphopy/__init__.py", line 169, in get_eigenvectors
    self.parameters.reduced_q_vector))
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/dynaphopy/interface/phonopy_link.py", line 117, in obtain_eigenvectors_and_frequencies
    phonon = get_phonon(structure)
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/dynaphopy/interface/phonopy_link.py", line 90, in get_phonon
    symprec=1e-5)
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/phonopy/api_phonopy.py", line 117, in __init__
    self._build_primitive_cell()
  File "/sfihome/djordje.dangic/anaconda2/envs/phonopy/lib/python3.7/site-packages/phonopy/api_phonopy.py", line 2955, in _build_primitive_cell
    raise RuntimeError(msg)
RuntimeError: Creating primitive cell is failed. PRIMITIVE_AXIS may be incorrectly specified.

Do you have any suggestions how to avoid this. Calculating DOS with MD works fine, as well as calculating power spectra (PS) projected on reciprocal lattice vector although results are a bit strange. I get phonons where I should not have any and the PS does not fall to zero for frequencies larger than Debye frequency from phonopy.

Thanks in advance,

Djordje

**Comment by abelcarreras** [comment]
Apparently there is some problem with the primitive cell definition.
I will need more detailed information to help you. 
Can you post the input file, structure, etc.. you are using?
Also what version of  phonopy are you using?

**Comment by DjordjeDangic** [comment]
Hello Mr. Carreras,

This is my POSCAR file of structure I used to generate mentioned supercells:

**Comment by abelcarreras** [comment]
Now I see the problem. Your definition of the primitive matrix is incorrect (maybe the name is misleading). Primitive matrix has to be written in fractional coordinates (respect to unit cell),
equivalent to primitive axis described in phonopy manual:

http://atztogo.github.io/phonopy/setting-tags.html?highlight=tag#primitive-axes-or-primitive-axis

**Comment by DjordjeDangic** [comment]
Thank you Mr. Carreras, i corrected my input file and now it works.

 However I still get non zero power spectra at high frequencies for acoustic modes at Gamma point and it is not single peaked but rather have multiple peaks. I have to fix my structure to run NVT to get phonons, could it be because my structure is not relaxed? Also should I be getting power spectra non zero at frequencies higher than Debye? I

**Comment by abelcarreras** [comment]
I'm not sure I understand you well, but in any case you definitely need to relax your structure to calculate the phonon force constants. You should check with phonopy that you have (at least) no imaginary harmonic frequencies at gamma. If the force constants (and therefore the phonon eigenvectors) are not properly calculated then you may get an unexpected behavior in the projections of the MD trajectory into the phonon modes.

**Comment by DjordjeDangic** [comment]
Thank you Mr. Carreras for your advice and patience. I am closing this issue now.
